global:
  scrape_interval: 15s

rule_files:
  - "aiops-alerts.yml"

scrape_configs:
  - job_name: "aiops_app"
    static_configs:
      - targets: ["172.31.12.194:5000"]

  - job_name: "aiops_ml_exporter"
    static_configs:
      - targets: ["172.31.12.194:8000"]

